---
abstract: 'Merges external application directories into your app.'
author:
  - 'Rodrigo de Oliveira <rodrigolive@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300021, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CatalystX-Features
requires:
  Carp: 0
  Catalyst: 5.80015
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0.25
  Catalyst::Plugin::Static::Simple: 0.27
  Class::Inspector: 0
  Config::General: 0
  FindBin: 0
  Moose: 0
  Path::Class: 0
  Test::More: 0.9
version: 0.24
